// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnXXF9Rf4HZcJ_eWDNdB6akVHzlyhhAP0',
    appId: '1:868806432422:web:b7e74edf6ffbdb16d60667',
    messagingSenderId: '868806432422',
    projectId: 'rentoy-online',
    authDomain: 'rentoy-online.firebaseapp.com',
    databaseURL: 'https://rentoy-online-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentoy-online.firebasestorage.app',
    measurementId: 'G-QWZZEXFVDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyOHm-qLbukRW7IANj7Z8tCMjGaT5B0w',
    appId: '1:868806432422:android:29a26ddc9d510848d60667',
    messagingSenderId: '868806432422',
    projectId: 'rentoy-online',
    databaseURL: 'https://rentoy-online-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentoy-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACCasyHEu6c8YH3RuEZ81NwpBnerdqwmk',
    appId: '1:868806432422:ios:c6a4011d3938f204d60667',
    messagingSenderId: '868806432422',
    projectId: 'rentoy-online',
    databaseURL: 'https://rentoy-online-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentoy-online.firebasestorage.app',
    iosBundleId: 'com.example.rentoy',
  );
}
